# Generated by Django 5.1.3 on 2025-10-20 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='solicitacao_professor',
            field=models.BooleanField(default=False),
        ),
    ]
