# Generated by Django 5.1.3 on 2025-10-20 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_perfil_solicitacao_professor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfil',
            options={'permissions': [('acessar_area_professor', 'Pode acessar a área de professor')]},
        ),
    ]
